version: '3.8'
services:
  app:
    build: ./docker
    volumes:
      - ./twitter:/var/www/twitter
    working_dir: /var/www/twitter
  nginx:
    image: nginx 
    ports:
      - 8083:80 
    volumes:
      - ./twitter:/var/www/twitter
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    build: ./docker/db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - twitter:/var/lib/mysql
volumes:
  twitter:
    driver: local